### ISSUE TITLE
(Reps) Review Contributors pending PRs

### ISSUE THREAD

**Issue by comzeradd** [mozilla/parsys#102]
Currently pending PRs:

- [ ] Only show current and future votes on the first vote listing page [1327](https://github.com/mozilla/remo/pull/1327)
- [x] Group top menu links [1323](https://github.com/mozilla/remo/pull/1323)
- [x] Misplaced down arrow, in select initiave dropbox [1314](https://github.com/mozilla/remo/pull/1314)

**Comment by comzeradd** [comment]
One more to go. @akatsoulas you had started reviewing that one initially. Let me know if I can help.

**Comment by akatsoulas** [comment]
@comzeradd if you have some time please go ahead and review the last one. Otherwise I will do it the first chance I will get.
