### ISSUE TITLE
Fix bitergia-es cluster

### ISSUE THREAD

**Issue by flamingspaz** [mozilla/parsys#128]
The bitergia cluster is acting up, opening this to track progress. Current status is that we're waiting on IT to reset our root account creds and buy AWS support for our account.

**Comment by flamingspaz** [comment]
We've got a support plan and I've opened a support case with AWS. Expecting a response in ~4 hours.

**Comment by flamingspaz** [comment]
> I have cut a ticket to the elasticsearch operations team to recover the node. I will update you as soon as I hear from them.

**Comment by sanacl** [comment]
ES is back!!! :D

**Comment by sanacl** [comment]
But it seems we can not create a new index. I'll stay tuned. Let me know when this is ready :)

**Comment by flamingspaz** [comment]
Updated the support ticket with the new information.

**Comment by flamingspaz** [comment]
This went fully operational again on Friday night
