### ISSUE TITLE
(Reps) (Bug) Point event venue in map don't works

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/parsys#130]
See [Bug 1346050](https://bugzilla.mozilla.org/show_bug.cgi?id=1346050)

Next step: Describe what needs to be done (API deprecated). Hope that a volunteer picks up

**Comment by hmitsch** [comment]
@couci will talk to volunteer Reps portal developers.

**Comment by Mte90** [comment]
I will try to look on it when I have time but in this period I am very busy.

**Comment by MichaelKohler** [comment]
No priority anymore, closing this.

**Comment by MichaelKohler** [comment]
eh, if I could.. @a-kilroy since you're on it, can you close this one as well?
