### ISSUE TITLE
Search UI Refactor

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/parsys#138]
This issue is a placeholder for the UI changes that we will need for the search refactor.

**Comment by akatsoulas** [comment]
Currently the only UI change required is in the template where the search results are displayed. Specifically, we need to unify the card which displays the profiles with the avatar with the card that displays the group results into one.

cc @comzeradd

**Comment by akatsoulas** [comment]
@comzeradd did you have the chance to review this?

**Comment by akatsoulas** [comment]
PR opened here:
https://github.com/mozilla/mozillians/pull/1718

**Comment by comzeradd** [comment]
Merged
