### ISSUE TITLE
Implement UI improvements to discourse-expose-emails-in

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/parsys#15]
* Change design of new topic and mailto buttons for logged in user:

![photo5787445569705322628](https://cloud.githubusercontent.com/assets/755354/23125304/03bab3ea-f769-11e6-8b2f-976b0754f3dc.jpg)

* Change design of new topic and mailto buttons for logged out user:

![photo5787445569705322632](https://cloud.githubusercontent.com/assets/755354/23125335/21f049e2-f769-11e6-89fd-b6b283198227.jpg)

* Add modal prompting a user to log in/sign up if they do click the disabled new topic button:

> You must be logged in to compose a new topic: [ Log in ]
> Alternatively, start a new topic by email: [ :email: ]

**Comment by LeoMcA** [comment]
### ➕ and ✉️ buttons

Right clicking a displayed ✉️ button, and selecting `Copy Email Address` should always copy the appropriate email address.

| |logged out (stranger)|logged in|
|-|-|-|
|**no email-in**| ➕ : greyed out, opens modal A <br> ✉️ : not displayed| ➕ : opens composer <br> ✉️ : not displayed|
|**no stranger email-in**| ➕ : greyed out, opens modal A <br> ✉️ : opens modal A| ➕ : opens composer <br> ✉️ : opens mail client|
|**all (including stranger) email-in**| ➕ : greyed out, opens modal B <br> ✉️ : opens mail client| ➕ : opens composer <br> ✉️ : opens mail client|

### Modals

If the ✉️ button isn't displayed outside of the modal, it shouldn't be displayed in it, but if it is displayed it should always open a mail client, rather than opening another modal.

*A:*
![A](https://cloud.githubusercontent.com/assets/755354/23370625/3a356272-fd0d-11e6-9be5-794a164860ba.png)

*B:*
![B](https://cloud.githubusercontent.com/assets/755354/23370627/3cb0aa34-fd0d-11e6-9662-3492ff63905f.png)

**Comment by viorelaioia** [comment]
Click on ![image](https://cloud.githubusercontent.com/assets/5293100/23409644/008e9494-fdd5-11e6-986a-d2394b99f5af.png) is not opening a mail client inside modal A or B; it has no effect.
See ![cannot open mail client](https://cloud.githubusercontent.com/assets/5293100/23409761/6ccbdc20-fdd5-11e6-899f-ffb79d70071a.png)

**Comment by LeoMcA** [comment]
> Click on envelope button when trying to start a new topic is not opening a mail client inside modal A or B; it has no effect.

@viorelaioia this should now be fixed on staging - can you confirm?
