### ISSUE TITLE
(Geodata) Use django-autocomplete to provide autocompletion for geocoding data.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/parsys#16]
* Provide autocompletion to geolocation drop-down fields.
* Limit choices based on the selection of another checkbox.

**Comment by viorelaioia** [comment]
Issues found: 

- Search after certain strings should return first countries that contain that start with those strings, and not countries that contain them:
![search for in](https://cloud.githubusercontent.com/assets/5293100/24159229/46e4f36e-0e67-11e7-84ca-1a4b3790b488.png)

- when "Country" is selected and "Region" is left empty,  "City" drop down options are not limited to the cities of the country selected:

- if selecting an option only for "City" drop down, the other fields are not auto-populated after click Update: https://vimeo.com/209416764

**Comment by viorelaioia** [comment]
Suggestion: make Timezone drop-down case insensitive (for consistency with the other drop-downs from Location section)
