### ISSUE TITLE
Filter after city/region/country from profile page shows no results

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/parsys#165]
Steps to reproduce:
1. Login to mozillians;
2. Navigate to profile page;
3. Click the Country set for your user; 

Expected results:
All mozillians from that country are shown;

Actual results: 
No results are shown;

Note: Same issue happens when selecting city or region, instead of country;

![filter after country shows no results](https://user-images.githubusercontent.com/5293100/27184958-6f926bb6-51ec-11e7-839c-5c4ea3e41506.png)

**Comment by viorelaioia** [comment]
Issue opened for https://github.com/mozilla/parsys/issues/116

**Comment by akatsoulas** [comment]
PR opened here:
https://github.com/mozilla/mozillians/pull/1737

**Comment by viorelaioia** [comment]
Reopen this, as we still don't get the expected results when filtering after city/region/country. 
Filter returns no results and "This field is required" message.

![filter](https://user-images.githubusercontent.com/5293100/27323780-788301f0-55ab-11e7-9a86-7481d16c0796.png)
