### ISSUE TITLE
Update message shown when searching for empty string 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/parsys#166]
STR:
1. Navigate to mozillians homepage;
2. Leave the search field empty and press enter;

Expected results:
A message informing the user that he/she should add a search key in order to get results should be shown;

Actual results:
"Sorry, we cannot find a group or person related to "". " message is shown;

**Comment by viorelaioia** [comment]
Issue opened for https://github.com/mozilla/parsys/issues/116

**Comment by akatsoulas** [comment]
PR opened here:
https://github.com/mozilla/mozillians/pull/1743
