### ISSUE TITLE
Long group name is not displayed correctly 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/parsys#168]
Steps to reproduce:
1. Login to mozillians;
2. Add "Berlin" key in the search box and press enter;
3. From "Advanced Options" select Groups and click Search button; 

Expected results:
Groups names are shown correctly for each group from the results.

Actual results:
The name is not shown correctly for one of the groups, it is truncated. See screenshot below. 

![group name not shown correctly](https://user-images.githubusercontent.com/5293100/27185927-78b1e03e-51ef-11e7-8360-415cae64f168.png)

**Comment by viorelaioia** [comment]
Issue opened for https://github.com/mozilla/parsys/issues/116

**Comment by comzeradd** [comment]
Merged on https://github.com/mozilla/mozillians/pull/1772
