### ISSUE TITLE
Update search results message based on Advanced Options filter

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/parsys#169]
STR:
1. Login to mozillians;
2. Enter a mozillian's name (e.g "Matt") in the search box and press enter;
3. From "Advanced Options" section select "Groups" and click Search button;

Expected results:
"Sorry, we cannot find a group related to "Matt". " message should be shown; The message should be personalized, based on what the user selected in Advanced Options (Groups or User profiles)

Actual results: 
"Sorry, we cannot find a group or person related to "Matt"." is shown;

**Comment by viorelaioia** [comment]
Issue opened for https://github.com/mozilla/parsys/issues/116

**Comment by akatsoulas** [comment]
PR opened here:
https://github.com/mozilla/mozillians/pull/1744
