### ISSUE TITLE
(Geodata) Upgrade django-autocomplete to the latest version.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/parsys#17]
* We need to refactor the way we populate the skills section.
* No breaking changes in the user dropdown fields.

**Comment by viorelaioia** [comment]
Tested this on mozillians-dev. Issues found during testing: 
- When trying to add an existing skill, we also get the option to create it 
![select skill issue](https://cloud.githubusercontent.com/assets/5293100/23704638/92733c9a-040e-11e7-9877-311e1a081820.png)

- Placeholder for skills field is not completely visible 
![placeholder not completely visible](https://cloud.githubusercontent.com/assets/5293100/23704664/b08c8bc8-040e-11e7-808f-db301e507c68.png)
