### ISSUE TITLE
Search results returned are limited to 20 results, pagination is not available

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/parsys#179]
STR:
1. Login to mozillians;
2. Add "Berlin" keyword in search input and press enter;

Expected results: 
All groups and user profiles that contain the "Berlin" keyword are shown; if search results will reach the number of results per page, results will be shown on next page (Not sure what is the limit of results/page)

Actual results: 
The search results message says "32 entries matching "berlin" ", but only 20 results (groups + user profiles) are displayed, pagination is not available. 
If filtering the results to show only user profiles, we still have 20 results displayed. 

![not all entries are shown on search results page](https://user-images.githubusercontent.com/5293100/27218987-b7e1384c-5288-11e7-9067-6676b8a5be2e.png)

![profiles](https://user-images.githubusercontent.com/5293100/27219048-e66208b8-5288-11e7-80f8-5943935f8eb7.png)

**Comment by viorelaioia** [comment]
opened for https://github.com/mozilla/parsys/issues/116

**Comment by johngian** [comment]
Fixed after
https://github.com/mozilla/mozillians/pull/1740
