### ISSUE TITLE
Searching after public username returns no results when anonymous

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/parsys#180]
STR:
1. Login to mozillians;
2. Navigate to profile page and set the username field to be public (http://imgur.com/fKgRB5h);
3. Logout;
4. Add the username from step 2 as keyword in the search box and press enter;

Expected results:
User's profile is returned, with the public fields displayed;

Actual results:
Search returns no results, message is shown. 

![search for username](https://user-images.githubusercontent.com/5293100/27226698-ee5b1396-52a8-11e7-8630-3260c0e25d68.png)

If searching after Name, which is public, the profile is returned. 
![search for name](https://user-images.githubusercontent.com/5293100/27226781-4253c0a6-52a9-11e7-809e-b01ee4a88b37.png)

**Comment by viorelaioia** [comment]
Opened for https://github.com/mozilla/parsys/issues/116

**Comment by akatsoulas** [comment]
PR opened here:
https://github.com/mozilla/mozillians/pull/1731
