### ISSUE TITLE
Update search box placeholder and message returned when search results = 0 for anonymous

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/parsys#181]
As users who are not logged in are allowed to see only public profiles (not groups), we should exclude the "groups" mention in the following places:
- search box placeholder, that currently says "Search for people, groups and more";
- the message returned when searching for a certain keyword returns no results, as it currently says "Sorry, we cannot find a group or person related to "x". "

**Comment by viorelaioia** [comment]
opened for https://github.com/mozilla/parsys/issues/116

**Comment by akatsoulas** [comment]
PR opened here:
https://github.com/mozilla/mozillians/pull/1744

**Comment by viorelaioia** [comment]
Reopen, as the message displayed for anonymous when the search returns no results is the same. 
See 
![message](https://user-images.githubusercontent.com/5293100/27325970-cb6e56ce-55b2-11e7-9cc3-bcc321bd06e9.png)

**Comment by akatsoulas** [comment]
Fixed here:
https://github.com/mozilla/mozillians/pull/1750
