### ISSUE TITLE
Profile photo visible only to mozillians is displayed to anonymous user

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/parsys#182]
Prerequisites:
Make sure the permission for profile photo of user "parsys_test" is set to "Mozillians". 

STR:
1. Navigate to mozillians-dev.allizom.org
2. Add "parsys_test" in the search box and click Enter 

Expected results:
Profile photo is not visible, the mozillians default one is shown;

Actual results:
The profile photo is visible to an anonymous user.

**Comment by viorelaioia** [comment]
Opened for https://github.com/mozilla/parsys/issues/116

**Comment by akatsoulas** [comment]
PR opened here:
https://github.com/mozilla/mozillians/pull/1741
