### ISSUE TITLE
Archive equalrating.com

### ISSUE THREAD

**Issue by flamingspaz** [mozilla/parsys#195]
Archive equalrating.com in the same way badges was done. Links should be changed to challenge.equalrating.com

**Comment by hmitsch** [comment]
@comzeradd can we keep the Analytics implementation intact with the archive? This would allow us to see if people still navigate the archive and how they get there.

**Comment by comzeradd** [comment]
I'll start the mirroring process.

@hmitsch I don't think Analytics would require any change, but I'll update you when mirroring is complete. We may need to alter the domain on GA too.

**Comment by flamingspaz** [comment]
@comzeradd did this a while ago, closing.
