### ISSUE TITLE
Implement a way to trigger reindexes

### ISSUE THREAD

**Issue by johngian** [mozilla/parsys#201]
Right now we only have the following ways to trigger an ES reindexing:

* Click the button in /admin
  * Right now this will fail because the underlying task is time limited
* Get shell access and run the command

Current issues with ES re-indexing:

* It takes a lot of time
* It wipes the working index and re-populates it from scratch
  * This means that we will not have good results while mozillians.org is getting reindexed

Things to implement

* Sane way to trigger reindexes from /admin that don't time-out
* Be able to re-index with the current ES index still up and then hot swap
* Take a look on how we can improve performance because current reindexing time is too much

**Comment by akatsoulas** [comment]
The patch is already deployed in prod.
