### ISSUE TITLE
Searching after a new group in mozillians stage redirects to prod 

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla/parsys#220]
**Steps to reproduce:**
1. Login to [mozillians stage](https://web-mozillians-staging.production.paas.mozilla.community/) and create a new group of any type.
2. Search after the group created in the previous step.
![perform search](https://user-images.githubusercontent.com/5293100/29672809-f0aa3d42-88f5-11e7-8ab8-80c5c245d9e5.png)
3. Click the group name in order to get to its page. 

**Expected results:**
Group page is displayed

**Actual results:**
User is redirected to the group in mozillians.org. 
![group page](https://user-images.githubusercontent.com/5293100/29672758-d36bc4b2-88f5-11e7-96e3-37b1ea843d76.png)

**Comment by flamingspaz** [comment]
It's fixed now. Absolute URLs use `SITE_URL` before the other settings, and by default `SITE_URL` is mozillians.org
