### ISSUE TITLE
Move remo planet feed to travis

### ISSUE THREAD

**Issue by flamingspaz** [mozilla/parsys#228]
So we don't have to pay for linode

- [x] Move mozillareps.org DNS to parsys
- [x] Move repo to the parsys org.
- [ ] Set up CF CDN

**Comment by akatsoulas** [comment]
cc @glogiotatidis. it seems that I cannot add you to the assignees for this issue.

**Comment by glogiotatidis** [comment]
Hey ready to do the transfer. where should I transfer this repo to?

**Comment by flamingspaz** [comment]
@glogiotatidis can you move it over to the mozilla-parsys org? or I think because of permissions on both sides it might be easier to give one of us owner access so we can move it?

**Comment by glogiotatidis** [comment]
> @glogiotatidis can you move it over to the mozilla-parsys org? or I think because of permissions on both sides it might be easier to give one of us owner access so we can move it?

B/c it's a personal repo and not a org-owned repo I can't give you admin access. I can't push it to mozilla-parsys either b/c I don't have write rights. 

Can you temporarily add me to mozilla-parsys to complete the transfer?

**Comment by glogiotatidis** [comment]
Also btw [planet.mozillareps.org](http://planet.mozillareps.org) since yesterday directs to reps.mozilla.org?

**Comment by flamingspaz** [comment]
Invited you to the org. I haven't opened the bug for DNS yet so I'm not sure what's up with the redirect.

**Comment by comzeradd** [comment]
curl planet.mozillareps.org
```
<html>
<head>
<title>Mozilla Reps</title>
<meta http-equiv="REFRESH" content="0;url=http://reps.mozilla.org"></HEAD>
<BODY>
Redirecting to Mozilla Reps Website
</BODY>
</HTML>
```

**Comment by glogiotatidis** [comment]
> Invited you to the org. I haven't opened the bug for DNS yet so I'm not sure what's up with the redirect.

Moved over. I also created a GitHub mozillareps user who should have pushed access to the repo. I'm not an admin anymore so I cannot verify.

Happy to send over mozillareps user credentials with you supply a GPG key

**Comment by glogiotatidis** [comment]
> I haven't opened the bug for DNS yet so I'm not sure what's up with the redirect.

Ah maybe the linode server freaked out right on time.

**Comment by glogiotatidis** [comment]
@flamingspaz admin rights on the repo under parsys would help me to setup travis

**Comment by flamingspaz** [comment]
Granted ya admin, you should be good to go.

**Comment by glogiotatidis** [comment]
And requested access for Travis CI to mozilla-parsys

**Comment by flamingspaz** [comment]
granted

**Comment by glogiotatidis** [comment]
OK Repo moved and setup as a daily cron-job. Github Pages configured to listen to planet.mozillareps.org.

Next step is DNS change.

**Comment by flamingspaz** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1400250

**Comment by flamingspaz** [comment]
I totally forgot, we need to set up Cloudfront in front of github pages for SSL.

**Comment by glogiotatidis** [comment]
FYI planet never had SSL. It would be nice to have but we don't need it to match current status and cloudfront as an option is not very attractive imo

**Comment by glogiotatidis** [comment]
Let's get one linode server less. Friendly ping @flamingspaz 🏓

**Comment by flamingspaz** [comment]
Oops yeah, totally forgot about this. I've changed the DNS and it looks like its working now.

**Comment by glogiotatidis** [comment]
Sweet! I'll go ahead and delete the linode server #229

**Comment by glogiotatidis** [comment]
I guess we can now close this one. Thanks all!

**Comment by flamingspaz** [comment]
I opened #235 to track adding SSL to the site. I know it didn't have it before but I don't think theres a good reason we shouldn't have it.

Thanks for your help @glogiotatidis!!
