### ISSUE TITLE
Delete linode MozillaReps2

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/parsys#229]
MozillaReps2 runs planet.mozillareps.org. 

When #228 gets fixed we can delete the VPS

**Comment by flamingspaz** [comment]
We're also paying for these servers on Linode, do we know what they do and can we turn them off too?

darnuria-server (Powered Off)
MozillaReps
mozsummitvoting (Powered Off)

**Comment by glogiotatidis** [comment]
I have no clue, maybe @ppapadeas can shed some light on this

**Comment by glogiotatidis** [comment]
The linode was removed, @flamingspaz can you please confirm before closing this out? The linode panel is not clear if that has been removed forever or just removed from my account.

**Comment by flamingspaz** [comment]
Yup, looks gone from here too.
