### ISSUE TITLE
Propose on-call rota

### ISSUE THREAD

**Issue by flamingspaz** [mozilla/parsys#23]

**Comment by flamingspaz** [comment]
Here's my proposal for oncall:
![Oncall](https://yalam.co.uk/i/_orx.png)
![Escalation Policy](https://yalam.co.uk/i/hsDQ.png)
Notes:
- Nemo and Tasos rotate their oncall weekly
- Nemo, Tasos and myself rotate weekend oncall weekly
- Tanner is oncall for community/parsys sites only

Any suggestions or things that are horribly wrong here?

/cc @cadecairos @johngian @akatsoulas @TannerFilip

**Comment by akatsoulas** [comment]
looks good to me

**Comment by johngian** [comment]
👍

**Comment by cadecairos** [comment]
LGTM

**Comment by TannerFilip** [comment]
![yeah](http://i.giphy.com/3o6Ztn7QsncvRY58ty.gif)
