### ISSUE TITLE
 Remo bot is not sending nomination emails for ROM

### ISSUE THREAD

**Issue by couci** [mozilla/parsys#231]
The last few months the Remo bot is not sending any emails to mentors to nominate the Rep of the Month. 

The result is that we only get 1 max 2 nominations per month.

I've also opened the [bug 1399820](https://bugzilla.mozilla.org/show_bug.cgi?id=1399820) for tracking reasons.

**Comment by akatsoulas** [comment]
The fix is deployed in prod. Closing for now
