### ISSUE TITLE
500 error when creating a new profile.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/parsys#238]
During profile creation we have the following error.

'AnonymousUser' object has no attribute 'userprofile'
```python
    def create_user(self, claims):
        user = super(MozilliansAuthBackend, self).create_user(claims)
        IdpProfile.objects.create(
            profile=self.request.user.userprofile,
            auth0_user_id=claims.get('user_id'),
            primary=True
        )
        return user
```

**Comment by viorelaioia-zz** [comment]
STR: 
1. Have an email address that has no mozillians account associated
2. Login to mozillians passwordless using that address

Expected: Registration page is shown
Actual: Error page is shown
Note: If repeating step 2 again, the registration page is shown

**Comment by akatsoulas** [comment]
PR opened here https://github.com/mozilla/mozillians/pull/1844
