### ISSUE TITLE
Q1 OKRs

### ISSUE THREAD

**Issue by flamingspaz** [mozilla/parsys#24]
@hmitsch can you confirm if this needs more work on it?

**Comment by hmitsch** [comment]
Yes it still needs work.

**Comment by hmitsch** [comment]
https://docs.google.com/spreadsheets/d/1wuF_0aONYtyfssUNqaHRsgOyOX1jmOTa84E5k0HBgYw/edit

**Comment by hmitsch** [comment]
Evaluation done last week.
