### ISSUE TITLE
Requesting URL newfirefox.mozilla.community

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/parsys#241]
As part of the Firefox Quantum release, we are doing a social media campaign with its own website. You can find out more here: https://docs.google.com/document/d/1KrLX6H63V64jD0iHpU6wc-l_j_P4Jpc1dQ2V8PvwASM/edit. For this we need newfirefox.mozilla.community set up by Friday evening (if possible), otherwise Monday very latest. Sorry for the short notice. 

Responsible staff member for this is @couci.

Repo: https://github.com/mozilla/newfirefox.mozilla.community
Relevant PR: https://github.com/mozilla/partinfra-terraform/pull/170

**Comment by hmitsch** [comment]
@flamingspaz can you take care of this?

**Comment by flamingspaz** [comment]
it's live at https://newfirefox.mozilla.community/, though im not sure it's fully working?

**Comment by MichaelKohler** [comment]
I would say it's working perfectly :)

Thanks!
