### ISSUE TITLE
P&E Sprint D Goal (including CoSS)

### ISSUE THREAD

**Issue by hmitsch** [mozilla/parsys#248]
# IAM
## London Work Week
- Kubernetes infrastructure
- TBD Henrik

# CoSS
## (TBD) Continue componentization 
P1 "Header with nav" P2 "Full width Feature" P3 "Full width quote" https://docs.google.com/document/d/1hT6gsF-CqoHaGqP0tTlkcVZKTQVqIdmV9YpPAjTBrmQ/edit
- Components are built
- Create front end of components
- engineering review meeting with Alan

## (TBD) _Themes in a can_
- 3 pre-built CSS themes exist in fractal, 1 theme demo'd in wagtail through demo page

## (TBD) Splash Rollout for Mozilla Designers
- Content kick-off has happened
- Splash builds a themes 
- Two Mozilla designer trainings have been scheduled

## (TBD) Simple Mozilla IAM Integration with Splash 
- Mozillians.org group `splash-access` allows users to log in to Splash as`administrators`.

## (TBD) Unified board for P&E team
- Decision on approach is made

## (TBD) Splash Salesforce Integration testing
- Review test cases: event signup, RSVP change/update, event time change, etc
- Execute tests
- Investigate test automation abilities
-Update Salesforce with needed data fields

# Rest of P&E

## Operations
- Runbook: its complete for Mozillians.org, still requires copy & paste for the other ParSys properties

## (TBD) Mozilla IAM Integration Consulting
- Integrate Common Voice with Mozilla IAM

## (TBD) Contributor PRs
- Merge any PRs?

## OSSN Sprint D
- (TBD) Rollout Discussion Utility Component for opensource.m.c
- training.m.c
- (TBD) Container hosting for GSoC

## Miscellaneous
- P&E Q1 & Q2 OKRs

Backlogged
- Themes are configured when the Website Utility is provisioned

**Comment by a-kilroy** [comment]
https://github.com/mozilla-parsys/coss/issues/27
