### ISSUE TITLE
After linking a new identity in mozillians, nlx tries to do the autologin with that identity 

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/parsys#249]
From @viorelaioia : (ported from https://github.com/mozilla-iam/auth0-custom-lock/issues/61)
STR:

    Login to sso.mozilla.com with github
    Click mozillians app -> you are autologged in with github
    Add a new google identity
    Go back to the dashboard and click Discourse

Expected:
User is autologged in with github

Actual:
User is autologged with google, as it remembers the most recent login type, which in this case is google.

Note:
This affects volunteers that need to verify their google accounts, in order to get access to team drive.

**Comment by gdestuynder** [comment]
Note: the fix should be to pass `prompt=none` parameter to /authorize when using autologin, and `prompt=` otherwise
Note2: since we now pass the other param (`tried...`) the easiest way is to pass both, so that it keeps working with NLX

**Comment by hidde** [comment]
So as per the standard, Mozillians will need to use `prompt=none` for login/autologin if possible, `prompt=` for something else. 

Would it make sense to use `prompt=select_account` for the screen where users go from Mozillians if they need to add an identity? (i.e. adding their Google email?) If I read the spec correctly and interpret broadly that could be the right parameter?

**Comment by gdestuynder** [comment]
Since we replace window.location automatically, Mozillians does not *need* to use `prompt=none` though it can of course (technically it makes the login even faster)

`prompt=select_account` would be right for the account verification functionality - and would be standard compliant (though I think we should probably *not* use oidc logins, as it creates new auth0 users, thus I consider these work-arounds)
