### ISSUE TITLE
(NEW) Reps Tweet Automation broken

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/parsys#278]
ParSys is hosting the ["GitHub Project Content Queue"](https://github.com/mozillach/gh-projects-content-queue/) which is used for [automating Reps tweets](https://github.com/mozilla/reps-tweets/issues). This has been down, or just not working, for quite some time now. Now I should have time to help debug this.

* Is the docker container running?
* If the docker container is running, can you run ```pm2 ls``` inside the container and send me the output?
* Also ```pm2 log --lines 1000``` might be interesting to see why it's not running correctly

Thanks in advance!

**Comment by johngian** [comment]
It looks like there is a config issue in the reps twitter automation side.
I sent @MichaelKohler the logs.

**Comment by MichaelKohler** [comment]
Thanks for the logs, was really helpful. @freaktechnik was so kind to fix the problem. 

@johngian could you please pull the latest image?

**Comment by MichaelKohler** [comment]
Thanks, @johngian. Working now as expected.
