### ISSUE TITLE
(Review) Add Mastodon as an external account.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/parsys#294]
https://discourse.mozilla.org/t/iam-coss-parsys-sprint-h-review/28144/2?u=hmitsch

**Comment by bunnybooboo** [comment]
IDK I might have been wrong with the @ shennanigans. For example here's Webfinger of my acct:
https://mastodon.social/.well-known/webfinger?resource=acct:david_ross@mastodon.social

**Comment by akatsoulas** [comment]
@bunnybooboo do you believe that having the @ before the username would be less confusing than having an 'email address'?
