### ISSUE TITLE
Domain: voice-sprint.mozilla.community

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/parsys#320]
For the upcoming Common Voice Sprint (also part of the Global Sprint) we are creating a website similar to firefoxsprint.mozilla.community. This will also be hosted on GitHub Pages and should be reachable through voice-sprint.mozilla.community.

Person responsible: @MichaelKohler
Person accountable within MoCo: @mikehenrty

PR will follow

**Comment by MichaelKohler** [comment]
PR: https://github.com/mozilla/partinfra-terraform/pull/189

**Comment by hmitsch** [comment]
@MichaelKohler not sure where it fits, so I will drop a comment here ...

Your GTM container ID is GTM-K5TVN23

Best regards,
   Henrik

**Comment by MichaelKohler** [comment]
Right, should have created a separate issue to better track. In any case, thanks a lot, will add tomorrow!

**Comment by hmitsch** [comment]
Also, this is the GA property ID: UA-84301250-13

GTM is setup and configured. Things should work as soon as you fire the container.

**Comment by MichaelKohler** [comment]
I've just added GTM, you should be seeing incoming data soon. Also nemo has done all necessary for the domain, so we're live here: http://voice-sprint.mozilla.community/

Thanks you two!

**Comment by hmitsch** [comment]
GA works ...

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/869692/39630216-00800f28-4faf-11e8-8bde-a32dd818c821.png">

Thank you!

**Comment by hmitsch** [comment]
Observatory score is still a B- ... that's not what we want to settle with, right?

https://observatory.mozilla.org/analyze.html?host=voice-sprint.mozilla.community

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/869692/39630396-7b06e0e6-4faf-11e8-81fe-ae56313d2570.png">


@MichaelKohler @johngian who of you can take care of this?

**Comment by MichaelKohler** [comment]
You don't like B-? How about A+? There you go..

https://observatory.mozilla.org/analyze.html?host=voice-sprint.mozilla.community
