### ISSUE TITLE
Update objects in the indices when a new Idp Profile account is added.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/parsys#321]

**Comment by hmitsch** [comment]
*Acceptance test:*

A search for https://mozillians.org/en-US/search/?q=mitsch returns only one result.

![image.png](https://images.zenhubusercontent.com/57641233bf93871ccd9cc8fe/9038d3d8-c90a-4666-a625-35ab76d94800)

**Comment by akatsoulas** [comment]
Closing as wontfix since the search service will be refactored.
