### ISSUE TITLE
Mozillians Org Chart: Link to Staff Profiles

### ISSUE THREAD

**Issue by hmitsch** [mozilla/parsys#326]
Acceptance Criteria:
* The org chart links to existing Staff profiles
* Work with UX Thomas & Hidde on the best quick visualization
* Design tweaks on /orgchart

**Comment by viorelaioia-zz** [comment]
I believe more work is needed for this task, as orgchart loading time is too high (~5 sec). 
Also, there are 2 bugs opened in mozillians repo for this ticket.
