### ISSUE TITLE
(NEW) Get aggregated data from mozillians for UX assesement. 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/parsys#355]

**Comment by johngian** [comment]
- external accounts per user (distribution: 10% have one, 25% have two etc.)
- most used external accounts (ranking: 1. 80% of all users have Twitter, 2. 70% GitHub etc.)
- total amount of access groups
- biggest access groups (ranking: 1. 80% of all users have NDA, 2. 70% Slack etc.) - Maybe TOP 20 is enough?
- total amount of tag groups
- biggest tag groups (ranking by popularity)
- total amount of skills
- list of skills (ranking by popularity)
