### ISSUE TITLE
(NEW) Google Analytics for supportsprint.mozilla.community

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/parsys#361]
Related: https://github.com/mozilla/parsys/issues/360

We would also like to setup GA the same way we did for firefoxsprint or voice-sprint. As always, GTM is fine. Would be great to have this by the end of the week so we can capture interest from the beginning.

/cc @hmitsch

**Comment by hmitsch** [comment]
**Google Analytics ID:** `UA-84301250-14`

This is wrapped via **Google Tag Manager container** `GTM-THZSLHH`, so please use that, if possible.

Please let me know once the container is integrated to the site to verify the configuration.

Best regards,
   Henrik

**Comment by MichaelKohler** [comment]
Thanks, will report back.

**Comment by MichaelKohler** [comment]
@hmitsch this should be live in about 5 minutes

**Comment by hmitsch** [comment]
For the record: GA tracking works.

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/869692/40628349-c4da40e6-62c4-11e8-9df9-472c2cfb7beb.png">


Sorry for the late answer.
Closing ticket.
