### ISSUE TITLE
Add Github username in Identity Profiles.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/parsys#377]
Linked issues ..
## Github
* [Make GitHub username searchable again](https://github.com/mozilla/mozillians/issues/2190)

## Bugzilla

┆Attachments: <a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5b0d30bb6d1d4ccbd5d7fbb3">Make GitHub username searchable again</a> | <a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5b14dc752f044c7fad600769">[staging] Error page shown on profile page for users with additional identities </a>

**Comment by ghost** [comment]
➤ Viorela Ioia commented:

Opened: https://github.com/mozilla/mozillians/issues/2361
