### ISSUE TITLE
(LDAP Integration) Integration evaluation criteria

### ISSUE THREAD

**Issue by johngian** [mozilla/parsys#4]
Prototype LDAP integration to mozillians.org

**Comment by hmitsch** [comment]
Next steps: 
* @hmitsch will create a doc with success criteria and a check-point meeting in approx. 48 hours.
* Following that we will have a decision on go/no-go for "Option 1/3 (SQL write)" and "Option 2 (python/django library)" prototypes

**Comment by hmitsch** [comment]
Evaluation document: https://docs.google.com/document/d/1QKzO1CPBlrHbKydpMhXcQJAUqXgh3OR-ok7Sb5JmMcY/edit#
