### ISSUE TITLE
Campus clubs group inbox on Discourse

### ISSUE THREAD

**Issue by flamingspaz** [mozilla/parsys#40]
Make campusclubs@ work in the same way as the Reps Council thing in Discourse

**Comment by LeoMcA** [comment]
Who should be the recepients of the emails? Are they going to change often? Are they already in a group in Discourse? In Mozillians?

**Comment by bacharakis** [comment]
The recipients will be Campus Clubs staff and ideally some community members.
No, they are not going to change often. 
Yes they are in NDAed Mozillians.

Thank you

**Comment by hmitsch** [comment]
@bacharakis can you please tell us specific names and Mozillians.org accounts of the above mentioned
* Campus Clubs staff
* the relevant community members?

**Comment by LeoMcA** [comment]
> Yes they are in NDAed Mozillians.

Great, that's also necessary, but I was more asking if there's a group in Mozillians which only contains the people you'd want to have access to the messages. If there was, we could sync it with Discourse, and then you could do the group management there.

> No, they are not going to change often.

But because of this, we can do the group mangement in Discourse as well. I've created a group for you, [campus_clubs](https://discourse.mozilla-community.org/groups/campus_clubs), and made you a group owner so you can add and remove members.

I'll work on setting up an email address you can forward emails to from campusclubs@ so discourse can recieve them.

**Comment by bacharakis** [comment]
So I just only need to add members to the discourse group?

That's amazing! 
Thank you guys!

Please let me know if you need anything else

**Comment by LeoMcA** [comment]
> So I just only need to add members to the discourse group?

To control who gets access to the shared inbox, yes. Make sure to tell people to set the shared inbox to watching (they can access it at: `https://discourse.mozilla-community.org/users/<username>/messages/group/campus_clubs`) to be notified for every message. Note that this doesn't apply the setting to past messages, so if you add members to the group after there's been some messages, they'll have to manually watch any message threads they're interested in.

Also note that the archived status of messages is shared across members of the group inbox - if you archive a message, it gets archived for everyone.

Also, if they want to be emailed despite being active on the site, they'll want to check the `Send me email notifications even when I am active on the site` preference under `https://discourse.mozilla-community.org/users/<username>/preferences`

We've still got a little bit of set-up on our end to accept emails, once we've done that I'll let you know what email address to set campusclubs@ (or whatever email you're wanting to accept emails from) to forward mail to, and then you'll be all set up and ready to go!

**Comment by bacharakis** [comment]
Hi @LeoMcA , do we have an update on this?

Cheers

**Comment by LeoMcA** [comment]
@bacharakis if you point campusclubs@mo.co to campus-clubs-group@mozilla-community.org you should be good to go!

Feel free to ping me if anything doesn't work as expected, or if you have any more questions.
