### ISSUE TITLE
Move reps_leadership Discourse group to Mozillians Access Group

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/parsys#435]
We currently have a Discourse group "reps_leadership". This is used for the Discourse inbox for mails to reps-council@mozilla.com. We decided that it makes sense to have access control in Mozillians only, therefore we would like to have a "Reps Leadership" Access Group.

**Name of the Access Group:**
reps_leadership

**Curators of this access group:**
* Ioana
* Nuke
* Konstantina

**Members of this access group:**
* https://mozillians.org/en-US/u/mkohler/
* https://mozillians.org/en-US/u/hmitsch/
* https://mozillians.org/en-US/u/IoanaChiorean/
* https://mozillians.org/en-US/u/ankitgadgil/
* https://mozillians.org/en-US/u/couci/
* https://mozillians.org/en-US/u/nukeador/
* https://mozillians.org/en-US/u/Mte90/
* https://mozillians.org/en-US/u/omudongo/
* https://mozillians.org/en-US/u/Mermi/
* https://mozillians.org/en-US/u/edovio/
* https://mozillians.org/en-US/u/Irvin/
* https://mozillians.org/en-US/u/prathamesh/
* https://mozillians.org/en-US/u/yomanpatil/

**Discourse "Inbox" to connect to this access group (without losing previous discussions):**
reps_leadership

**Related Reps issue:**
https://github.com/mozilla/Reps/issues/343

/cc @LeoMcA @hmitsch 

Thanks in advance!

**Comment by MichaelKohler** [comment]
As only staff can create access groups, Leo suggested that @hmitsch creates the group. @hmitsch would you mind? :)

**Comment by hmitsch** [comment]
Group created: https://mozillians.org/group/reps_leadership/

The membership renewal is set to **200 days**.

**Comment by MichaelKohler** [comment]
Thanks!

**Comment by LeoMcA** [comment]
After testing that everyone had their profiles set up correctly (and prompting @MichaelKohler to help a few users do that) I've set the Discourse [reps_leadership](https://discourse.mozilla.org/groups/reps_leadership) group to be managed by Mozillians.

**Comment by MichaelKohler** [comment]
Great, thanks a lot! Works like a charm!
