### ISSUE TITLE
(Community Sites) Bug 1342698: Next steps with mozillausa.org

### ISSUE THREAD

**Issue by hmitsch** [mozilla/parsys#55]
https://bugzilla.mozilla.org/show_bug.cgi?id=1342698

**Comment by flamingspaz** [comment]
We've decided that we'll stop the server until they've figured out what they're going to do with it.

**Comment by floatingatoll** [comment]
Webops redirected traffic to the domain to blog.mozilla.org temporarily until a resolution is reached. Please let them know in-bug when y'all come up with a plan, so they can clean up any leftover bits.
