### ISSUE TITLE
Create a new registration page for mozillians.org

### ISSUE THREAD

**Issue by comzeradd** [mozilla/parsys#57]
Based on [Wireframes](https://github.com/mozilla/iam-project-backlog/issues/24).

**Comment by m-branson** [comment]
@comzeradd where in the new prototypes does this page exist? Currently I see registration existing at the sign up form and then a user having the ability to adjust profile settings in the 'settings' page. Does this align with what you're thinking?

**Comment by comzeradd** [comment]
Yes, this issue is to track the first part. The Sign Up form. Not the lock authorization and not the Settings page. But the form that you need to fill some basic personal information (eg. full name, location), before you start using the website.
