### ISSUE TITLE
(Infra Mig) Verify reps email address

### ISSUE THREAD

**Issue by flamingspaz** [mozilla/parsys#63]
We need to be able to send as reps@m.c

- [x] Add DKIM/SPF record
- [ ] Verify in SES

Alt: Use an address @mozilla.community

**Comment by MichaelKohler** [comment]
What is this for? For mails from the portal? Something else?

**Comment by flamingspaz** [comment]
Yep, mail sent from the portal.

**Comment by flamingspaz** [comment]
We're using reps@m.community for this.
