### ISSUE TITLE
(Infra Mig) Reps switchover

### ISSUE THREAD

**Issue by flamingspaz** [mozilla/parsys#89]
https://bugzilla.mozilla.org/show_bug.cgi?id=1349215

**Comment by flamingspaz** [comment]
DNS change was done, but I'm not calling this closed until celery from the old infra is switched off

https://bugzilla.mozilla.org/show_bug.cgi?id=1349361

**Comment by tyearns** [comment]
Currently blocked until Yousef returns from vacation.

**Comment by flamingspaz** [comment]
Celery is down for reals now, so we can call this done!
